modify
W3cplus/webgl-fundamentals-zh pull request #3
Opened 2016-09-26 11:21 UTC by JimmyVV

amend previous problem

2016-09-27 02:06 UTC, Ovilia commented on _book/2D-translation/WebGL-2D-Matrices.html
> +            gitbook.page.hasChanged({"page":{"title":"WebGL 2D Matrices","level":"1.4.4","depth":2,"next":{"title":"3D","level":"1.5","depth":1,"path":"3D/README.md","ref":"3D/README.md","articles":[
这些文件根本没改就不要 add 进来了吧（可能是换行符不同操作系统的区别）

2016-09-27 02:06 UTC, Ovilia commented on fundamentals/WebGL-How-It-Works.md
> +如果你使用一个单位大小的 buffer 的单一类型的数据的话，那么步长和偏移量总是 0。步长为 0 意味着 “每个步长包括了数据的类型和大小”。偏移量为 0 意味着数据从 buffer 的起始位开始. 将他们设置为其他值而不是 0 来说, 会更复杂，尽管这样做在性能方面有些好处。不过，相对于复杂度来说，这并不值得，除非你是想让 WebGL 受它绝对的限制。
这里还是有标点的问题，全局再查一下~辛苦！

2016-09-27 02:27 UTC, JimmyVV commented on fundamentals/WebGL-How-It-Works.md
> +如果你使用一个单位大小的 buffer 的单一类型的数据的话，那么步长和偏移量总是 0。步长为 0 意味着 “每个步长包括了数据的类型和大小”。偏移量为 0 意味着数据从 buffer 的起始位开始. 将他们设置为其他值而不是 0 来说, 会更复杂，尽管这样做在性能方面有些好处。不过，相对于复杂度来说，这并不值得，除非你是想让 WebGL 受它绝对的限制。
恩。没问题。

2016-09-27 02:29 UTC, JimmyVV commented on _book/2D-translation/WebGL-2D-Matrices.html
> +            gitbook.page.hasChanged({"page":{"title":"WebGL 2D Matrices","level":"1.4.4","depth":2,"next":{"title":"3D","level":"1.5","depth":1,"path":"3D/README.md","ref":"3D/README.md","articles":[
这个主要是 gitbook serve 时，重新编译的配置文件。那我把 _book 添加到 .gitignore 里面吧。

2016-09-28 12:24 UTC, JimmyVV commented
这里改动有点大。主要是将 _book 的track 给删除了。所以导致 _book 文件目录没有了。不过，通过 git init 和 git book 可以本地生成，这里就直接 rm --cached。 然后，完成了 《WebGL 工作原理》英文的移除 和 《WebGL 着色器和 GLSL》这篇的翻译。

2016-09-28 12:40 UTC, JimmyVV commented
如果在 git pull 的时候遇到 conflic. 可以执行 git rm -r _book . 然后再 git pull 就没问题了。

2016-09-29 02:27 UTC, Ovilia requested changes
这次翻译质量提高非常多，赞一下👍

2016-09-29 02:27 UTC, Ovilia commented on fundamentals/WebGL-Shaders-and-GLSL.md
> +在 [WebGL 的工作原理][3]中，我们提到过，当你每次绘制图像时，WebGL 需要两个着色器。一个是顶点着色器，一个是片元着色器。顶点着色器和片元着色器在一个着色器程序中(或者说就是 程序 )。一个典型的 WebGL app 会包含很多着色器程序。
半角括号与空格

2016-09-29 02:27 UTC, Ovilia commented on fundamentals/WebGL-Shaders-and-GLSL.md
> +然后， 在绘制之前，我们需要设置 uniform 的值
逗号后多余空格（真佩服我自己，怎么这都看出来了😳）

2016-09-29 02:27 UTC, Ovilia commented on fundamentals/WebGL-Shaders-and-GLSL.md
> +GLSL 全称是 Graphics Library Shader Language. 着色器就是用这种语言写的。他有一写特殊的半独特的功能，这些功能在 JavaScript 里面是不常见的。它设计的初衷就是做一些数学运算，将计算的结果用来栅格化图像。所以，例如，他有一些内置的类型，像 vec2，vec3，和 vec4，分别代表着 2 个值，3个值，和4个值。另外，他还有 mat2，mat3 和
半角句号

2016-10-10 02:40 UTC, Ovilia approved these changes

2016-10-10 02:40 UTC, merged